spring:
  application:
    name: file-storage
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/file_storage}
server:
  port: ${SERVER_PORT:8080}

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
  expiration: ${JWT_EXPIRATION:3600000} # 1 hour in milliseconds

# Logging Configuration
logging:
  level:
    root: INFO
    lambdalabs.filestorage: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.mongodb.driver: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/file-storage.log
    max-size: 10MB
    max-history: 30

---
spring:
  config:
    activate:
      on-profile: test
  data:
    mongodb:
      uri: mongodb://localhost:27017/file_storage_test
