name: Docker Build

on:
  push:
    branches: [ main, develop ]
    paths:
      - '**/*.java'
      - 'pom.xml'
      - 'Dockerfile'
      - 'docker-compose.yml'
      - '.github/workflows/docker-build.yml'
      - 'src/**'
  pull_request:
    branches: [ main, develop ]

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (no push)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: file-storage:ci
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
